In [24]:
import numpy as np

## DataTypes and Attributes


In [25]:
# Numpy's main data type is ndarray

a1 = np.array([1, 2, 3])
a1


array([1, 2, 3])

In [26]:
type(a1)

numpy.ndarray

In [27]:
a2 = np.array([ [1, 2, 3], [4, 5.5, 6.6] ])
a3 = np.array([ [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])


In [28]:
a2
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
type(a3)

numpy.ndarray

In [30]:
a1.shape

(3,)

In [31]:
a2.shape

(2, 3)

In [32]:
a3.shape

(1, 3, 3)

In [33]:
### Number of dimensions
a3.ndim, a2.ndim 

(3, 2)

In [34]:
a1.size

3

In [35]:
## Create a DataFrame from a Numpy array
import pandas as pd
a2
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.5  6.6

## 2. Creating arrays

In [36]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [37]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
zeroes = np.zeros( [2,3])
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

## Practical Examples

<img src="images/numpy-panda.jpeg" />

In [42]:
## Turn an image into a NumPy array
from matplotlib.image import imread
panda = imread("images/numpy-panda.jpeg")
print(type(panda))

<class 'numpy.ndarray'>


In [43]:
panda.size, panda.shape, panda.ndim

(3271680, (852, 1280, 3), 3)

In [46]:
panda[:5] # read the first 5

array([[[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [41, 34, 24]],

       [[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       [[13, 26, 16],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       [[13, 26, 16],
        [14, 27, 17],
        [13, 29, 18],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       [[13, 26, 16],
        [14, 27, 17],
        [13, 29, 18],
        ...,
        [43, 34, 25],
        [42, 33, 24],
        [42, 33, 24]]], dtype=uint8)

<img src="images/numpy-car-photo.png"/>

In [48]:
car = imread("images/numpy-car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


<img src="images/numpy-dog-photo.png"/>

In [49]:
dog = imread("images/numpy-dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>
